version: 0.2.{build}
image: Visual Studio 2019 Preview
build_script:
- ps: >-
    nuget restore "src\\Shiba.sln"

    msbuild "src\\Shiba.sln" /m /verbosity:minimal /p:Configuration=Release

    nuget pack "src\\Shiba.nuspec" -Version $env:appveyor_build_version
    
artifacts:
- path: '*.nupkg'
  name: nuget
deploy:
- provider: Environment
  name: nuget
  on:
    branch: master
